[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]

#dev config
env = "dev"
port = 443

#databse config
[db]
client = "postgres"
host = "127.0.0.1"
port = 8888
database = "test_db"
user = "postgres"
password = "abcd"

#redis config
[redis]
host = "127.0.0.1"
port = 5432
password = ""

#jwt config
[jwt]
jwt_key = "key"
jwt_cookie =""