
env = "dev" #xxxxxx
port = 443 

#databse config
[db]
client = "postgres"
database = "test_db"
host = "127.0.0.1"
password = "abcd"
port = 8888
user = "postgres"

#redis config
[redis]
host = "127.0.0.1"
password = ""
port = 5432

#jwt config
[jwt]
jwt_cookie = ""
jwt_key = "key"
